import fs from 'fs';
import path from 'path';
import { generateVirtualGridCode } from './virtual-grid.js';
import { validateContractAndIR } from './validate-contract-ir.js';



export function validateRuntimeAPI(ir) {
  const contractPath = 'contracts/runtime-api.contract.json';
  if (!fs.existsSync(contractPath)) return;
  const runtimeApi = JSON.parse(fs.readFileSync(contractPath, 'utf8'));

  const jsonStr = JSON.stringify(ir);
  // Fail if IR hallucinates sharedMap.observe
  if (jsonStr.includes('sharedMap.observe')) {
    throw new Error('Validation failed: generated IR references undefined runtime API sharedMap.observe');
  }

  // Validate forbidden methods
  for (const method of runtimeApi.domRules.forbiddenMethods) {
    if (jsonStr.includes(method) || (ir.create && ir.create.template && ir.create.template.includes(method))) {
      throw new Error(`Validation failed: generated IR uses forbidden runtime API ${method}`);
    }
  }
}

export function generateComponent(contract, ir, contractPath, irPath, outPath) {
  validateContractAndIR(contract, ir);
  validateRuntimeAPI(ir);

  const componentName = ir.name || (ir.module ? path.basename(ir.module).split('.')[0] : 'unknown-component');
  const fnName = 'create' + componentName.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');

  let code = `// Generated by Fe generator.
// Source contract: ${contractPath}
// Source IR: ${irPath}
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

`;

  if (ir.children) {
    const childImports = new Set();
    for (const child of ir.children) {
      childImports.add(child.component);
    }
    for (const comp of childImports) {
      const childFnName = 'create' + comp.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
      code += `import { ${childFnName} } from './${comp}.generated.js';\n`;
    }
    code += `\n`;
  }

  // Helper functions
  code += `function safeClassToken(val) {
  if (val == null) return '';
  return String(val).toLowerCase().replace(/[^a-z0-9-]/g, '-');
}

function formatCurrency(val) {
  if (val == null) return '';
  return '$' + Number(val).toFixed(2);
}
`;

  code += `export function ${fnName}(initialState = {}, eventSink = () => {}) {\n`;
  code += `  const template = document.createElement('template');\n`;
  const escapedTemplate = ir.create.template.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
  code += `  template.innerHTML = \`${escapedTemplate}\`;\n  \n`;
  code += `  const root = template.content.firstElementChild.cloneNode(true);\n`;

  // References
  const refVars = [];
  for (const [refName, selector] of Object.entries(ir.create.refs)) {
    if (refName === 'root') continue;
    code += `  const ${refName}Element = root.matches(\`${selector}\`) ? root : root.querySelector(\`${selector}\`);\n`;
    refVars.push(refName);
  }
  
  if (ir.lists) {
    for (const list of ir.lists) {
      const listCap = list.name.charAt(0).toUpperCase() + list.name.slice(1);
      code += `\n  // List management for ${list.name}\n`;
      code += `  const ${list.name}Instances = new Map();\n`;
      code += `  function insert${listCap}(${list.itemKey}, instance) {\n`;
      code += `    ${list.name}Instances.set(${list.itemKey}, instance);\n`;
      code += `    ${list.ref}Element.appendChild(instance.root);\n`;
      code += `  }\n`;
      code += `  function remove${listCap}(${list.itemKey}) {\n`;
      code += `    const instance = ${list.name}Instances.get(${list.itemKey});\n`;
      code += `    if (instance) {\n`;
      code += `      if (instance.root.parentNode === ${list.ref}Element) ${list.ref}Element.removeChild(instance.root);\n`;
      code += `      ${list.name}Instances.delete(${list.itemKey});\n`;
      code += `    }\n`;
      code += `  }\n`;
      code += `  function reconcile${listCap}Order(itemKeys) {\n`;
      if (list.countRef) {
        code += `    ${list.countRef}Element.textContent = String(itemKeys.length);\n`;
      }
      code += `    for (const key of itemKeys) {\n`;
      code += `      const instance = ${list.name}Instances.get(key);\n`;
      code += `      if (instance) ${list.ref}Element.appendChild(instance.root);\n`;
      code += `    }\n`;
      code += `  }\n`;
    }
  }
  
  if (ir.children) {
    code += `\n  // Children\n`;
    code += `  const children = {};\n`;
    for (const child of ir.children) {
      const childFnName = 'create' + child.component.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
      const propsObj = child.staticProps ? JSON.stringify(child.staticProps) : '{}';
      code += `  children['${child.name}'] = ${childFnName}(${propsObj}, eventSink);\n`;
      code += `  ${child.container}Element.appendChild(children['${child.name}'].root);\n`;
    }
    code += `\n`;
  }
  
  // Text node setup for things that use setTextNodeValue
  if (ir.patches) {
    for (const patch of ir.patches) {
      for (const op of patch.ops) {
        if (op.op === 'setTextNodeValue') {
          code += `  const ${op.ref}TextNode = document.createTextNode('');\n`;
          code += `  ${op.ref}Element.appendChild(${op.ref}TextNode);\n`;
        }
      }
    }
  }

  code += `\n`;

  // State vars
  if (ir.patches) {
    for (const patch of ir.patches) {
      code += `  let current${patch.input.charAt(0).toUpperCase() + patch.input.slice(1)};\n`;
    }
  }
  code += `\n`;

  // Patch functions
  if (ir.patches) {
    for (const patch of ir.patches) {
    const varName = `current${patch.input.charAt(0).toUpperCase() + patch.input.slice(1)}`;
    code += `  function ${patch.name}(nextVal) {
    if (${varName} === nextVal) return;
    ${varName} = nextVal;
`;
    for (const op of patch.ops) {
      const target = op.ref === 'root' ? 'root' : op.ref + 'Element';
      if (op.op === 'setTextNodeValue') {
        if (op.format === 'currency') {
          code += `    ${op.ref}TextNode.nodeValue = formatCurrency(nextVal);\n`;
        } else {
          code += `    ${op.ref}TextNode.nodeValue = nextVal == null ? '' : String(nextVal);\n`;
        }
      } else if (op.op === 'setTextContent') {
        if (op.prefix) {
          code += `    ${target}.textContent = nextVal == null ? '' : \`${op.prefix}\${String(nextVal)}\`;\n`;
        } else {
          code += `    ${target}.textContent = nextVal == null ? '' : String(nextVal);\n`;
        }
      } else if (op.op === 'setClassToken') {
        code += `    ${target}.className = nextVal == null ? \`${op.prefix.trim()}\` : \`${op.prefix}\${safeClassToken(nextVal)}\`;\n`;
      } else if (op.op === 'setClassName') {
        code += `    ${target}.className = nextVal ? \`${op.trueClass}\` : \`${op.falseClass}\`;\n`;
      } else if (op.op === 'setAttribute') {
        code += `    if (nextVal == null || nextVal === false) { ${target}.removeAttribute('${op.attr}'); } else { ${target}.setAttribute('${op.attr}', nextVal === true ? 'true' : nextVal); }\n`;
      } else if (op.op === 'setBooleanAttribute') {
        code += `    if (nextVal) { ${target}.setAttribute('${op.attr}', '${op.trueValue}'); } else { ${target}.setAttribute('${op.attr}', '${op.falseValue}'); }\n`;
      } else if (op.op === 'setStyleDisplay') {
        code += `    ${target}.style.display = nextVal ? '${op.trueDisplay}' : '${op.falseDisplay}';\n`;
      } else if (op.op === 'setSparklinePath') {
        code += `    if (!nextVal || !nextVal.length) { ${target}.setAttribute('d', ''); } else {
      const max = Math.max(...nextVal);
      const min = Math.min(...nextVal);
      const range = max - min || 1;
      const step = 100 / (nextVal.length - 1 || 1);
      const d = nextVal.map((v, i) => (i === 0 ? 'M' : 'L') + (i * step) + ',' + (30 - ((v - min) / range) * 30)).join(' ');
      ${target}.setAttribute('d', d);
    }\n`;
      } else if (op.op === 'setInputProperty') {
        code += `    if (${target}.value !== nextVal) ${target}.value = nextVal == null ? '' : nextVal;\n`;
      } else if (op.op === 'setCheckboxProperty') {
        code += `    if (${target}.checked !== !!nextVal) ${target}.checked = !!nextVal;\n`;
      } else if (op.op === 'reconcileList') {
        code += `    reconcile${op.listName.charAt(0).toUpperCase() + op.listName.slice(1)}Order(nextVal);\n`;
      }
    }
    code += `  }\n\n`;
    }
  }

  if (ir.virtualGrids) {
    for (const grid of ir.virtualGrids) {
      code += generateVirtualGridCode(grid);
    }
  }

  // Events
  const handlers = [];
  if (ir.events) {
    for (const ev of ir.events) {
      const handlerName = ev.name || 'undefined';
      code += `  function handle${handlerName}(event) {\n`;
      code += `      eventSink({ type: '${ev.emits}', sourceEvent: event });\n`;
      code += `    }\n`;
      code += `    ${ev.target === 'root' ? 'root' : ev.target + 'Element'}.addEventListener('${ev.type}', handle${handlerName});\n\n`;
      handlers.push({ ...ev, handlerName });
    }
  }
  // Master patch
  code += `  function patch(nextState) {
    if (!nextState) return;
`;
  if (ir.virtualGrids) {
    for (const grid of ir.virtualGrids) {
      code += `    patchVirtualGrid(nextState);\n`;
    }
  }
  if (ir.patches) {
    for (const patch of ir.patches) {
      code += `    if (nextState.${patch.input} !== undefined) ${patch.name}(nextState.${patch.input});\n`;
    }
  }
  code += `  }\n\n`;

  // Dispose
  code += `  function dispose() {\n`;
  for (const ev of handlers) {
    code += `    ${ev.target === 'root' ? 'root' : ev.target + 'Element'}.removeEventListener('${ev.type}', handle${ev.name || 'undefined'});\n`;
  }
  if (ir.lists) {
    for (const list of ir.lists) {
      code += `    ${list.name}Instances.clear();\n`;
    }
  }
  if (ir.children) {
    code += `    for (const child of Object.values(children)) child.dispose();\n`;
  }
  code += `  }\n\n`;

  let exportObj = `root, patch, dispose`;
  if (ir.lists) {
    for (const list of ir.lists) {
      const listCap = list.name.charAt(0).toUpperCase() + list.name.slice(1);
      exportObj += `, insert${listCap}, remove${listCap}, reconcile${listCap}Order`;
    }
  }
  if (ir.children) {
    exportObj += `, children`;
  }
  if (ir.virtualGrids) {
    exportObj += `, patchVirtualCell`;
  }

  code += `  patch(initialState);\n\n`;
  code += `  return { ${exportObj} };\n`;
  code += `}\n`;

  // 2. Generate Component Test Suite
  let testCode = `// Generated by Fe generator.
// Source contract: ${contractPath}
// Source IR: ${irPath}
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { ${fnName} } from './${path.basename(outPath)}';

describe('${fnName} Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = ${fnName}({});
    expect(root).toBeDefined();
  });

`;
  const hasTitlePatch = ir.patches?.some(p => p.input === 'title');
  if (ir.create.refs.titleNode && hasTitlePatch) {
    testCode += `  test('HTML-looking title renders as safe text, not markup', () => {
    const { root } = ${fnName}({ title: '<script>alert(1)</script><b>Bold</b>' });
    const titleHtml = root.querySelector('${ir.create.refs.titleNode}')?.innerHTML || '';
    expect(titleHtml).toContain('&lt;script&gt;');
    expect(titleHtml).not.toContain('<script>');
  });\n\n`;
  }

  // Generate patch tests dynamically based on ops
  if (ir.patches) {
    for (const patch of ir.patches) {
      testCode += `  test('patch ${patch.input} precisely updates DOM', () => {\n`;
      testCode += `    const { root, patch } = ${fnName}({});\n`;
      for (const op of patch.ops) {
        const selector = ir.create.refs[op.ref];
        if (op.op === 'setTextContent') {
          const val = 'TestVal123';
          const expected = op.prefix ? op.prefix + val : val;
          testCode += `    patch({ ${patch.input}: '${val}' });\n`;
          testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.textContent).toBe('${expected}');\n`;
        } else if (op.op === 'setClassToken') {
          const val = 'SomeVal';
          const expected = op.prefix + 'someval';
          testCode += `    patch({ ${patch.input}: '${val}' });\n`;
          testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.className).toBe('${expected}');\n`;
        } else if (op.op === 'setAttribute') {
          const val = 'TestAttr';
          testCode += `    patch({ ${patch.input}: '${val}' });\n`;
          testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.getAttribute('${op.attr}')).toBe('${val}');\n`;
        }
      }
      testCode += `  });\n\n`;
    }
  }
  
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, code, 'utf8');
  console.log('Generated:', outPath);

  // Generate event listener and dispose tests
  testCode += `  test('events are emitted and cleaned up on dispose', () => {\n`;
  testCode += `    const sink = vi.fn();\n`;
  testCode += `    const { root, dispose } = ${fnName}({}, sink);\n`;
  
  if (ir.events) {
    for (const ev of ir.events) {
      const selector = ir.create.refs[ev.target];
      testCode += `    root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.dispatchEvent(new window.Event('${ev.type}'));\n`;
      testCode += `    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: '${ev.emits}' }));\n`;
      testCode += `    sink.mockClear();\n`;
    }

    testCode += `    dispose();\n`;
    for (const ev of ir.events) {
      const selector = ir.create.refs[ev.target];
      testCode += `    root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.dispatchEvent(new window.Event('${ev.type}'));\n`;
      testCode += `    expect(sink).not.toHaveBeenCalled();\n`;
    }
  }

  testCode += `  });\n\n`;
  testCode += `});\n`;

  const testOutPath = outPath.replace('.js', '.test.js');
  fs.writeFileSync(testOutPath, testCode, 'utf8');
  console.log('Generated:', testOutPath);
}

function runCLI() {
  const irPath = process.argv[2] || 'ir/kanban-card.ir.json';
  const outPath = process.argv[3]; // Optional

  const irRaw = fs.readFileSync(irPath, 'utf8');
  const ir = JSON.parse(irRaw);

  const componentName = path.basename(ir.module || irPath).split('.')[0].replace('.ir', '');
  const contractPath = `contracts/${componentName}.contract.json`;
  
  const contractRaw = fs.readFileSync(contractPath, 'utf8');
  const contract = JSON.parse(contractRaw);

  const finalOutPath = outPath || (ir.module ? ir.module : `generated-examples/${componentName}/${componentName}.generated.js`);
  
  generateComponent(contract, ir, contractPath, irPath, finalOutPath);
}

import { fileURLToPath } from 'url';
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCLI();
}
