import fs from 'fs';
import path from 'path';
import { validateContractAndIR } from './validate-contract-ir.js';

const irPath = process.argv[2] || 'ir/kanban-card.ir.json';
const outPath = process.argv[3]; // Optional

function generate(irPath, outPath) {
  const irRaw = fs.readFileSync(irPath, 'utf8');
  const ir = JSON.parse(irRaw);

  const componentName = path.basename(ir.module).split('.')[0];
  const contractPath = `contracts/${componentName}.contract.json`;
  
  const contractRaw = fs.readFileSync(contractPath, 'utf8');
  const contract = JSON.parse(contractRaw);

  validateContractAndIR(contract, ir);

  const fnName = 'create' + componentName.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');

  // 1. Generate Component JS
  let code = `// Generated by Fe generator.
// Source contract: ${contractPath}
// Source IR: ${irPath}
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

`;

  // Helper functions
  code += `function safeClassToken(val) {
  if (val == null) return '';
  return String(val).toLowerCase().replace(/[^a-z0-9-]/g, '-');
}

function formatCurrency(val) {
  if (val == null) return '';
  return '$' + Number(val).toFixed(2);
}

export function ${fnName}(initialState = {}, eventSink = () => {}) {
  const template = document.createElement('template');
  template.innerHTML = \`${ir.create.template}\`;
  
  const root = template.content.firstElementChild.cloneNode(true);
`;

  // References
  const refVars = [];
  for (const [refName, selector] of Object.entries(ir.create.refs)) {
    if (refName === 'root') continue;
    code += `  const ${refName}Element = root.matches(\`${selector}\`) ? root : root.querySelector(\`${selector}\`);\n`;
    refVars.push(refName);
  }
  
  // Text node setup for things that use setTextNodeValue
  for (const patch of ir.patches) {
    for (const op of patch.ops) {
      if (op.op === 'setTextNodeValue') {
        code += `  const ${op.ref}TextNode = document.createTextNode('');\n`;
        code += `  ${op.ref}Element.appendChild(${op.ref}TextNode);\n`;
      }
    }
  }

  code += `\n`;

  // State vars
  for (const patch of ir.patches) {
    code += `  let current${patch.input.charAt(0).toUpperCase() + patch.input.slice(1)};\n`;
  }
  code += `\n`;

  // Patch functions
  for (const patch of ir.patches) {
    const varName = `current${patch.input.charAt(0).toUpperCase() + patch.input.slice(1)}`;
    code += `  function ${patch.name}(nextVal) {
    if (${varName} === nextVal) return;
    ${varName} = nextVal;
`;
    for (const op of patch.ops) {
      const target = op.ref === 'root' ? 'root' : op.ref + 'Element';
      if (op.op === 'setTextNodeValue') {
        if (op.format === 'currency') {
          code += `    ${op.ref}TextNode.nodeValue = formatCurrency(nextVal);\n`;
        } else {
          code += `    ${op.ref}TextNode.nodeValue = nextVal == null ? '' : String(nextVal);\n`;
        }
      } else if (op.op === 'setTextContent') {
        if (op.prefix) {
          code += `    ${target}.textContent = nextVal == null ? '' : \`${op.prefix}\${String(nextVal)}\`;\n`;
        } else {
          code += `    ${target}.textContent = nextVal == null ? '' : String(nextVal);\n`;
        }
      } else if (op.op === 'setClassToken') {
        code += `    ${target}.className = nextVal == null ? \`${op.prefix.trim()}\` : \`${op.prefix}\${safeClassToken(nextVal)}\`;\n`;
      } else if (op.op === 'setClassName') {
        code += `    ${target}.className = nextVal ? \`${op.trueClass}\` : \`${op.falseClass}\`;\n`;
      } else if (op.op === 'setAttribute') {
        code += `    if (nextVal == null || nextVal === false) { ${target}.removeAttribute('${op.attr}'); } else { ${target}.setAttribute('${op.attr}', nextVal === true ? 'true' : nextVal); }\n`;
      } else if (op.op === 'setBooleanAttribute') {
        code += `    if (nextVal) { ${target}.setAttribute('${op.attr}', '${op.trueValue}'); } else { ${target}.setAttribute('${op.attr}', '${op.falseValue}'); }\n`;
      } else if (op.op === 'setStyleDisplay') {
        code += `    ${target}.style.display = nextVal ? '${op.trueDisplay}' : '${op.falseDisplay}';\n`;
      }
    }
    code += `  }\n\n`;
  }

  // Events
  const handlers = [];
  for (const ev of ir.events) {
    code += `  function handle${ev.name}(event) {
    eventSink({ type: '${ev.emits}', sourceEvent: event });
  }
  ${ev.target === 'root' ? 'root' : ev.target + 'Element'}.addEventListener('${ev.type}', handle${ev.name});\n\n`;
    handlers.push(ev);
  }

  // Master patch
  code += `  function patch(nextState) {
    if (!nextState) return;
`;
  for (const patch of ir.patches) {
    code += `    if (nextState.${patch.input} !== undefined) ${patch.name}(nextState.${patch.input});\n`;
  }
  code += `  }\n\n`;

  // Dispose
  code += `  function dispose() {
`;
  for (const ev of handlers) {
    if (ev.cleanup) {
      code += `    ${ev.target === 'root' ? 'root' : ev.target + 'Element'}.removeEventListener('${ev.type}', handle${ev.name});\n`;
    }
  }
  code += `  }\n\n`;

  code += `  patch(initialState);\n\n`;
  code += `  return { root, patch, dispose };\n`;
  code += `}\n`;

  // 2. Generate Component Test Suite
  let testCode = `// Generated by Fe generator.
// Source contract: ${contractPath}
// Source IR: ${irPath}
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { ${fnName} } from './${path.basename(ir.module)}';

describe('${fnName} Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = ${fnName}({});
    expect(root).toBeDefined();
  });

  test('HTML-looking title renders as safe text, not markup', () => {
    const { root } = ${fnName}({ title: '<script>alert(1)</script><b>Bold</b>' });
    const titleHtml = root.querySelector('${ir.create.refs.titleNode}')?.innerHTML || '';
    expect(titleHtml).toContain('&lt;script&gt;');
    expect(titleHtml).not.toContain('<script>');
  });

`;

  // Generate patch tests dynamically based on ops
  for (const patch of ir.patches) {
    testCode += `  test('patch ${patch.input} precisely updates DOM', () => {\n`;
    testCode += `    const { root, patch } = ${fnName}({});\n`;
    for (const op of patch.ops) {
      const selector = ir.create.refs[op.ref];
      if (op.op === 'setTextContent') {
        const val = 'TestVal123';
        const expected = op.prefix ? op.prefix + val : val;
        testCode += `    patch({ ${patch.input}: '${val}' });\n`;
        testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.textContent).toBe('${expected}');\n`;
      } else if (op.op === 'setClassToken') {
        const val = 'SomeVal';
        const expected = op.prefix + 'someval';
        testCode += `    patch({ ${patch.input}: '${val}' });\n`;
        testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.className).toBe('${expected}');\n`;
      } else if (op.op === 'setAttribute') {
        const val = 'TestAttr';
        testCode += `    patch({ ${patch.input}: '${val}' });\n`;
        testCode += `    expect(root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.getAttribute('${op.attr}')).toBe('${val}');\n`;
      }
    }
    testCode += `  });\n\n`;
  }
  const finalOutPath = outPath || ir.module;
  fs.mkdirSync(path.dirname(finalOutPath), { recursive: true });
  fs.writeFileSync(finalOutPath, code, 'utf8');
  console.log('Generated:', finalOutPath);

  // Generate event listener and dispose tests
  testCode += `  test('events are emitted and cleaned up on dispose', () => {\n`;
  testCode += `    const sink = vi.fn();\n`;
  testCode += `    const { root, dispose } = ${fnName}({}, sink);\n`;
  
  for (const ev of ir.events) {
    const selector = ir.create.refs[ev.target];
    testCode += `    root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.dispatchEvent(new window.Event('${ev.type}'));\n`;
    testCode += `    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: '${ev.emits}' }));\n`;
    testCode += `    sink.mockClear();\n`;
  }

  testCode += `    dispose();\n`;
  for (const ev of ir.events) {
    const selector = ir.create.refs[ev.target];
    testCode += `    root${selector === '[data-node="root"]' ? '' : `.querySelector('${selector}')`}.dispatchEvent(new window.Event('${ev.type}'));\n`;
    testCode += `    expect(sink).not.toHaveBeenCalled();\n`;
  }

  testCode += `  });\n\n`;
  testCode += `});\n`;

  const testOutPath = finalOutPath.replace('.js', '.test.js');
  fs.writeFileSync(testOutPath, testCode, 'utf8');
  console.log('Generated:', testOutPath);
}

const args = process.argv.slice(2);
if (args[0]) {
  generate(args[0], args[1]);
} else {
  console.error("Usage: node generator/index.js <path-to-ir.json> [output-path]");
  process.exit(1);
}
