// Generated by Fe generator.
// Source contract: contracts/kanban-card.contract.json
// Source IR: ir/kanban-card.ir.json
// Do not edit for human aesthetics.
// Regenerate from contract/IR.

import { describe, test, expect, vi } from 'vitest';
import { createKanbanCard } from './kanban-card.generated.js';

describe('createKanbanCard Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createKanbanCard({});
    expect(root).toBeDefined();
  });

  test('HTML-looking title renders as safe text, not markup', () => {
    const { root } = createKanbanCard({ title: '<script>alert(1)</script><b>Bold</b>' });
    const titleHtml = root.querySelector('[data-node="titleNode"]')?.innerHTML || '';
    expect(titleHtml).toContain('&lt;script&gt;');
    expect(titleHtml).not.toContain('<script>');
  });

  test('patch id precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ id: 'TestAttr' });
    expect(root.getAttribute('data-id')).toBe('TestAttr');
  });

  test('patch title precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ title: 'TestVal123' });
    expect(root.querySelector('[data-node="titleNode"]').textContent).toBe('TestVal123');
  });

  test('patch description precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ description: 'TestVal123' });
    expect(root.querySelector('[data-node="descNode"]').textContent).toBe('TestVal123');
  });

  test('patch status precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ status: 'TestVal123' });
    expect(root.querySelector('[data-node="statusBadge"]').textContent).toBe('TestVal123');
    patch({ status: 'SomeVal' });
    expect(root.querySelector('[data-node="statusBadge"]').className).toBe('badge-status status-someval');
  });

  test('patch priority precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ priority: 'TestVal123' });
    expect(root.querySelector('[data-node="priorityBadge"]').textContent).toBe('TestVal123');
    patch({ priority: 'SomeVal' });
    expect(root.querySelector('[data-node="priorityBadge"]').className).toBe('badge-priority priority-someval');
  });

  test('patch assignee precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ assignee: 'TestVal123' });
    expect(root.querySelector('[data-node="assigneeNode"]').textContent).toBe('Assigned to: TestVal123');
  });

  test('patch lockedBy precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ lockedBy: 'TestVal123' });
    expect(root.querySelector('[data-node="lockIndicator"]').textContent).toBe('🔒 Locked by TestVal123');
  });

  test('patch updatedAt precisely updates DOM', () => {
    const { root, patch } = createKanbanCard({});
    patch({ updatedAt: 'TestAttr' });
    expect(root.querySelector('[data-node="timeNode"]').getAttribute('datetime')).toBe('TestAttr');
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createKanbanCard({}, sink);
    root.querySelector('[data-node="editBtn"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'kanban:item:edit' }));
    sink.mockClear();
    root.querySelector('[data-node="deleteBtn"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'kanban:item:delete' }));
    sink.mockClear();
    root.dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'kanban:item:select' }));
    sink.mockClear();
    root.querySelector('[data-node="dragHandle"]').dispatchEvent(new window.Event('dragstart'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'card:dragstart' }));
    sink.mockClear();
    dispose();
    root.querySelector('[data-node="editBtn"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="deleteBtn"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="dragHandle"]').dispatchEvent(new window.Event('dragstart'));
    expect(sink).not.toHaveBeenCalled();
  });

});
