// Generated by Fe generator.
// Source contract: contracts/live-dashboard-widget.contract.json
// Source IR: ir/live-dashboard-widget.ir.json
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { createLiveDashboardWidget } from './live-dashboard-widget.generated.js';

describe('createLiveDashboardWidget Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createLiveDashboardWidget({});
    expect(root).toBeDefined();
  });

  test('HTML-looking title renders as safe text, not markup', () => {
    const { root } = createLiveDashboardWidget({ title: '<script>alert(1)</script><b>Bold</b>' });
    const titleHtml = root.querySelector('[data-node="titleNode"]')?.innerHTML || '';
    expect(titleHtml).toContain('&lt;script&gt;');
    expect(titleHtml).not.toContain('<script>');
  });

  test('patch id precisely updates DOM', () => {
    const { root, patch } = createLiveDashboardWidget({});
    patch({ id: 'TestAttr' });
    expect(root.getAttribute('data-widget-id')).toBe('TestAttr');
  });

  test('patch title precisely updates DOM', () => {
    const { root, patch } = createLiveDashboardWidget({});
    patch({ title: 'TestVal123' });
    expect(root.querySelector('[data-node="titleNode"]').textContent).toBe('TestVal123');
  });

  test('patch currentValue precisely updates DOM', () => {
    const { root, patch } = createLiveDashboardWidget({});
  });

  test('patch history precisely updates DOM', () => {
    const { root, patch } = createLiveDashboardWidget({});
  });

  test('patch status precisely updates DOM', () => {
    const { root, patch } = createLiveDashboardWidget({});
    patch({ status: 'SomeVal' });
    expect(root.className).toBe('widget-root status-someval');
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createLiveDashboardWidget({}, sink);
    dispose();
  });

});
