// Generated by Fe generator.
// Source contract: contracts/settings-form.contract.json
// Source IR: ir/settings-form.ir.json
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { createSettingsForm } from './settings-form.generated.js';

describe('createSettingsForm Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createSettingsForm({});
    expect(root).toBeDefined();
  });

  test('patch username precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch email precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch notificationsEnabled precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch theme precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch usernameError precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
    patch({ usernameError: 'TestVal123' });
    expect(root.querySelector('#usernameError').textContent).toBe('TestVal123');
  });

  test('patch usernameErrorVisible precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch emailError precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
    patch({ emailError: 'TestVal123' });
    expect(root.querySelector('#emailError').textContent).toBe('TestVal123');
  });

  test('patch emailErrorVisible precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
  });

  test('patch isSubmitting precisely updates DOM', () => {
    const { root, patch } = createSettingsForm({});
    patch({ isSubmitting: 'TestAttr' });
    expect(root.querySelector('#saveBtn').getAttribute('disabled')).toBe('TestAttr');
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createSettingsForm({}, sink);
    root.querySelector('#settingsForm').dispatchEvent(new window.Event('submit'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'settings:submit' }));
    sink.mockClear();
    root.querySelector('#settingsForm').dispatchEvent(new window.Event('input'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'settings:input' }));
    sink.mockClear();
    dispose();
    root.querySelector('#settingsForm').dispatchEvent(new window.Event('submit'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('#settingsForm').dispatchEvent(new window.Event('input'));
    expect(sink).not.toHaveBeenCalled();
  });

});
