// Generated by Fe generator.
// Source contract: contracts/demo-shell.contract.json
// Source IR: ir/demo-shell.ir.json
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { createDemoShell } from './demo-shell.generated.js';

describe('createDemoShell Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createDemoShell({});
    expect(root).toBeDefined();
  });

  test('patch activeRoute precisely updates DOM', () => {
    const { root, patch } = createDemoShell({});
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navKanban"]').getAttribute('data-active')).toBe('TestAttr');
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navGrid"]').getAttribute('data-active')).toBe('TestAttr');
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navDashboard"]').getAttribute('data-active')).toBe('TestAttr');
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navSettings"]').getAttribute('data-active')).toBe('TestAttr');
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navCatalog"]').getAttribute('data-active')).toBe('TestAttr');
    patch({ activeRoute: 'TestAttr' });
    expect(root.querySelector('[data-node="navOps"]').getAttribute('data-active')).toBe('TestAttr');
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createDemoShell({}, sink);
    root.querySelector('[data-node="navKanban"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:kanban' }));
    sink.mockClear();
    root.querySelector('[data-node="navGrid"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:grid' }));
    sink.mockClear();
    root.querySelector('[data-node="navDashboard"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:dashboard' }));
    sink.mockClear();
    root.querySelector('[data-node="navSettings"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:settings' }));
    sink.mockClear();
    root.querySelector('[data-node="navCatalog"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:catalog' }));
    sink.mockClear();
    root.querySelector('[data-node="navOps"]').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'demo:nav:ops' }));
    sink.mockClear();
    dispose();
    root.querySelector('[data-node="navKanban"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="navGrid"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="navDashboard"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="navSettings"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="navCatalog"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('[data-node="navOps"]').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
  });

});
