// Generated by Fe generator.
// Source contract: contracts/data-grid.contract.json
// Source IR: ir/data-grid.ir.json
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { createDataGrid } from './data-grid.generated.js';

describe('createDataGrid Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createDataGrid({});
    expect(root).toBeDefined();
  });

  test('patch filterText precisely updates DOM', () => {
    const { root, patch } = createDataGrid({});
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createDataGrid({}, sink);
    root.querySelector('#gridSearch').dispatchEvent(new window.Event('input'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'grid:search:input' }));
    sink.mockClear();
    dispose();
    root.querySelector('#gridSearch').dispatchEvent(new window.Event('input'));
    expect(sink).not.toHaveBeenCalled();
  });

});
