// Generated by Fe generator.
// Source contract: contracts/product-card.contract.json
// Source IR: ir/product-card.ir.json
// Regenerate with: npm run generate
// Do not edit for human aesthetics.
// Generated code is optimized for LLM continuation and direct browser patching.

import { describe, test, expect, vi } from 'vitest';
import { createProductCard } from './product-card.generated.js';

describe('createProductCard Machine-Generated Tests', () => {

  test('initial render null/missing values gracefully', () => {
    const { root } = createProductCard({});
    expect(root).toBeDefined();
  });

  test('patch title precisely updates DOM', () => {
    const { root, patch } = createProductCard({});
    patch({ title: 'TestVal123' });
    expect(root.querySelector('#productTitle').textContent).toBe('TestVal123');
  });

  test('patch price precisely updates DOM', () => {
    const { root, patch } = createProductCard({});
    patch({ price: 'TestVal123' });
    expect(root.querySelector('#productPrice').textContent).toBe('$TestVal123');
  });

  test('patch img precisely updates DOM', () => {
    const { root, patch } = createProductCard({});
    patch({ img: 'TestAttr' });
    expect(root.querySelector('#productImg').getAttribute('src')).toBe('TestAttr');
  });

  test('events are emitted and cleaned up on dispose', () => {
    const sink = vi.fn();
    const { root, dispose } = createProductCard({}, sink);
    root.querySelector('#addToCartBtn').dispatchEvent(new window.Event('click'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'catalog:add_to_cart' }));
    sink.mockClear();
    root.querySelector('#productImg').dispatchEvent(new window.Event('load'));
    expect(sink).toHaveBeenCalledWith(expect.objectContaining({ type: 'catalog:img_load' }));
    sink.mockClear();
    dispose();
    root.querySelector('#addToCartBtn').dispatchEvent(new window.Event('click'));
    expect(sink).not.toHaveBeenCalled();
    root.querySelector('#productImg').dispatchEvent(new window.Event('load'));
    expect(sink).not.toHaveBeenCalled();
  });

});
